# -*- coding: utf-8 -*-
"""
Ollama Service -- LLM Description Stage
=========================================
Adapter layer for the language model.

To swap the model (phi3:mini <-> llama3.2:3b <-> mistral <-> any future model):
    - Change OLLAMA_MODEL in your .env file -- that is ALL, no code change needed.

To swap the LLM provider entirely (Ollama <-> OpenAI <-> local llama.cpp):
    - Only change _run_real() below.
    - Function signature and return shape must stay identical.

Input (from pipeline.jpg stage 4):
    blip_result  -- contains an English scene caption from BLIP
    user_query   -- optional Turkish question transcribed by STT (Stage 1)

Turkish output:
    System prompt uses proper Turkish characters (ş, ı, ğ, ü, ö, ç).
    This produces cleaner TTS output from Edge TTS neural voices.
"""

import asyncio
import re
import time
import random
from typing import Any

from core.config import settings
from core.logger import logger


# ---------------------------------------------------------------------------
# Prompt templates — proper Turkish characters for clean TTS output
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = (
    "Sen görme engelli kullanıcılara yardım eden bir görsel asistansın. "
    "SADECE Türkçe yaz. Asla Çince, Arapça veya başka dil kullanma. "
    "Sana noktalı virgülle ayrılmış birden fazla İngilizce sahne açıklaması verilecek; "
    "bunlar aynı sahnenin farklı bölgelerinden alınmış anlık görüntülerdir. "
    "Görevin: bu açıklamaları sentezleyerek Türkçe 1-2 kompakt cümleye dönüştürmek. "
    "Kurallar: "
    "1) Tüm açıklamaları birleştir, en önemli nesne/kişiyi öne çıkar. "
    "2) İngilizce nesne adlarını doğru Türkçeye çevir: "
    "   oatmeal=yulaf ezmesi, spoon=kaşık, gun=silah, pills=ilaç hapı, "
    "   box=kutu, bag=torba/paket, clock tower=saat kulesi, cookie=kurabiye. "
    "3) Tanıdık bir marka veya ilaç adı görürsen (örn: Kreon, Lifalif), adını söyle "
    "   ve ne olduğunu 2-3 kelimeyle belirt (örn: Kreon, sindirim ilacı). "
    "4) SADECE Türkçe yaz, asla liste veya tire kullanma. "
    "5) Yön ifadesi kullan: elinizde / önünüzde / arkanızda. "
    "6) Cevap maksimum 2 Türkçe cümle olmalı. "
    "Örnek giriş: 'person holding Kreon pills box; another box in background' "
    "Örnek çıkış: 'Elinizde Kreon sindirim ilacı kutusu var, arkada başka bir kutu görünüyor.'"
)

_SYSTEM_PROMPT_WITH_QUERY = (
    "Sen görme engelli kullanıcılara yardım eden bir görsel asistansın. "
    "SADECE Türkçe yaz. Asla Çince, Arapça veya başka dil kullanma. "
    "Sana noktalı virgülle ayrılmış birden fazla İngilizce sahne açıklaması ve "
    "kullanıcının Türkçe sorusu verilecek. "
    "Görevin: soruyu tüm açıklamaları kullanarak Türkçe 1-2 cümleyle yanıtlamak. "
    "Kurallar: "
    "1) Tüm açıklamaları değerlendir, soruyla en ilgili bilgiyi öne çıkar. "
    "2) İngilizce nesne adlarını doğru Türkçeye çevir. "
    "3) Tanıdık marka/ilaç adı varsa adını ve kısa açıklamasını ver. "
    "4) SADECE Türkçe yaz, asla liste veya tire kullanma. "
    "5) Cevap maksimum 2 Türkçe cümle olmalı. "
)

_SYSTEM_OCR_CHECK = (
    "You must answer with exactly one word: yes or no. Nothing else. "
    "Does this scene contain objects where reading printed text would help a blind person? "
    "Answer YES for: medicine/pill/drug/tablet boxes, labels with dosage, prescriptions, "
    "signs, receipts, menus, product ingredient lists, documents. "
    "Answer NO for: food without visible labels, people, nature, furniture, games, vehicles. "
    "One word answer only:"
)

# Appended in post-processing (not generated by LLM) when OCR is recommended
_OCR_OFFER = " Üzerindeki yazıları okumamı ister misiniz?"

_USER_PROMPT_SCENE = "Sahne açıklamaları (İngilizce): {caption}\n\nBu sahneyi Türkçe 1-2 cümleyle açıkla."

_USER_PROMPT_QUERY = (
    "Kullanıcı sorusu: {user_query}\n"
    "Sahne açıklamaları (İngilizce): {caption}\n\n"
    "Soruyu yanıtlayarak Türkçe 1-2 cümleyle açıkla."
)


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------

async def run_ollama(
    blip_result: dict[str, Any],
    user_query: str | None = None,
    history: list[dict] | None = None,
) -> dict[str, Any]:
    """
    Generate a Turkish scene description from the BLIP caption.

    Args:
        blip_result: Output of blip_service.run_blip() — contains "caption".
        user_query:  Optional transcribed user question from STT (Stage 1).
        history:     Conversation history for context-aware follow-ups.
                     List of {user, assistant} dicts, max last 3 exchanges.

    Returns:
        { "description": str, "latency_ms": float }
    """
    if settings.mock_ollama:
        return await _run_mock(blip_result, user_query)
    return await _run_real(blip_result, user_query, history or [])


# ---------------------------------------------------------------------------
# Implementation: Mock
# ---------------------------------------------------------------------------

_MOCK_DESCRIPTIONS_TR = [
    "Önünüzde bir kapı var, solunuzda bir sandalye bulunuyor.",
    "Masanın üzerinde dizüstü bilgisayar ve bardak var, sağınızda pencere görünüyor.",
    "Duvara yaslanmış bir bisiklet var, bir kişi size doğru geliyor.",
    "Bir ofis ortamındasınız, etrafta masalar ve sandalyeler var.",
    "Solunuzda bir araba park edilmiş, karşıda bina girişi görünüyor.",
]

_MOCK_QUERY_RESPONSES_TR = [
    "Önünüzde büyük bir nesne bulunuyor, dikkatli olun.",
    "Yolunuzda herhangi bir engel görünmüyor.",
    "Kapı solunuzda, yaklaşık iki metre uzaklıkta.",
]


async def _run_mock(
    blip_result: dict[str, Any],
    user_query: str | None,
) -> dict[str, Any]:
    t = time.monotonic()
    logger.info("Ollama [mock] | caption=%s | query=%s",
                blip_result["caption"], repr(user_query))
    await asyncio.sleep(settings.mock_ollama_delay_ms / 1000)
    if user_query:
        description = random.choice(_MOCK_QUERY_RESPONSES_TR)
    else:
        description = random.choice(_MOCK_DESCRIPTIONS_TR)
    latency = round((time.monotonic() - t) * 1000, 2)
    logger.info("Ollama [mock] done | %.1fms", latency)
    return {"description": description, "latency_ms": latency}


# ---------------------------------------------------------------------------
# Implementation: Real Ollama HTTP API
# ---------------------------------------------------------------------------

async def _run_real(
    blip_result: dict[str, Any],
    user_query: str | None,
    history: list[dict],
) -> dict[str, Any]:
    """
    Calls the Ollama HTTP API at settings.ollama_base_url.
    Model is set via OLLAMA_MODEL in .env — no code change needed to swap models.
    History is injected into the prompt for context-aware follow-ups.
    """
    import httpx

    t = time.monotonic()
    caption = blip_result["caption"]

    # Build history context (inject as background info, not dialogue format)
    history_text = ""
    if history:
        prev = [h["assistant"] for h in history[-2:] if h.get("assistant")]
        if prev:
            history_text = "Önceki açıklama: " + " | ".join(prev) + "\n\n"

    base_payload = {
        "model": settings.ollama_model,
        "stream": False,
        "options": {"temperature": 0.2, "num_predict": 100, "num_ctx": settings.ollama_num_ctx},
    }

    logger.info("Ollama [real] | model=%s | query=%s | caption=%s",
                settings.ollama_model, repr(user_query), caption[:60])

    # B3: Separate connect timeout (3s fast-fail) from read timeout (full budget)
    timeout = httpx.Timeout(settings.ollama_timeout_seconds, connect=3.0)

    try:
        async with httpx.AsyncClient(timeout=timeout) as client:
            # Call 1: OCR detection first (fast yes/no) — result feeds into description
            ocr_response = await client.post(
                f"{settings.ollama_base_url}/api/generate",
                json={**base_payload,
                      "system": _SYSTEM_OCR_CHECK,
                      "prompt": caption,
                      "options": {"temperature": 0.0, "num_predict": 3}},
            )
            ocr_response.raise_for_status()
            ocr_raw = ocr_response.json().get("response", "").strip().lower()
            ocr_recommended = ocr_raw.startswith("yes")

            # Call 2: Description — includes OCR offer suffix when reading would help
            if user_query:
                system_prompt = _SYSTEM_PROMPT_WITH_QUERY
                user_prompt = history_text + _USER_PROMPT_QUERY.format(
                    user_query=user_query, caption=caption
                )
            else:
                system_prompt = _SYSTEM_PROMPT
                user_prompt = history_text + _USER_PROMPT_SCENE.format(caption=caption)

            desc_response = await client.post(
                f"{settings.ollama_base_url}/api/generate",
                json={**base_payload, "system": system_prompt, "prompt": user_prompt},
            )
            desc_response.raise_for_status()
            description = _clean_output(desc_response.json().get("response", ""))

            # Append OCR offer as post-processing (not LLM-generated — keeps description fast)
            if ocr_recommended:
                description = description.rstrip(".!?") + "." + _OCR_OFFER

    except httpx.ConnectError:
        raise RuntimeError(
            f"Ollama is unreachable at {settings.ollama_base_url}. "
            "Make sure Ollama is running: ollama serve"
        )
    except httpx.TimeoutException:
        raise RuntimeError(
            f"Ollama timed out after {settings.ollama_timeout_seconds}s. "
            f"Model '{settings.ollama_model}' may still be loading — try again in a moment."
        )

    latency = round((time.monotonic() - t) * 1000, 2)
    logger.info("Ollama [real] done | %.1fms | ocr=%s | output=%s",
                latency, ocr_recommended, description[:80])
    return {"description": description, "ocr_recommended": ocr_recommended, "latency_ms": latency}


# ---------------------------------------------------------------------------
# JSON output parser — extracts description + ocr_recommended from LLM response
# ---------------------------------------------------------------------------

def _clean_output(raw: str) -> str:
    """Strip LLM formatting artifacts so Edge TTS reads clean sentences."""
    text = raw.strip()
    text = re.sub(r'^[^\n]{0,60}:\s*\n', '', text, flags=re.IGNORECASE)
    text = re.sub(r'^\s*[-*•]\s*', '', text, flags=re.MULTILINE)
    text = re.sub(r'\s*\([a-zA-Z ]+\)', '', text)
    text = text.strip('"\'')
    text = re.sub(r'\s+', ' ', text).strip()
    return text
